// Generated by ego.
// DO NOT EDIT

package example_ego
import (
"fmt"
"html"
"io"
"strings"
)
var _ = fmt.Sprint("") // just so that we can keep the fmt import for now
//line example_template.ego:1
 func MyTmpl(w io.Writer, u *User) error  {
//line example_template.ego:2
_, _ = io.WriteString(w, "\n\n")
//line example_template.ego:4
_, _ = io.WriteString(w, "\n\n<html>\n  <body>\n    <h1>Hello ")
//line example_template.ego:7
_, _ = io.WriteString(w, html.EscapeString(fmt.Sprintf("%v",  strings.TrimSpace(u.FirstName) )))
//line example_template.ego:7
_, _ = io.WriteString(w, "!</h1>\n\n    <p>Here's a list of your favorite colors:</p>\n    <ul>\n      ")
//line example_template.ego:11
 for _, colorName := range u.FavoriteColors { 
//line example_template.ego:12
_, _ = io.WriteString(w, "\n        <li>")
//line example_template.ego:12
_, _ = io.WriteString(w, html.EscapeString(fmt.Sprintf("%v",  colorName )))
//line example_template.ego:12
_, _ = io.WriteString(w, "</li>\n      ")
//line example_template.ego:13
 } 
//line example_template.ego:14
_, _ = io.WriteString(w, "\n    </ul>\n  </body>\n</html>\n")
return nil
}
